### PR TITLE
Changing the existing method test

### PR DESCRIPTION
**Pull request by simonc**
Hi,

I modified the way the existence of a method is tested.
I guess the single '=' sign was a typo. I replaced it by an .include? call.

Cheers,

### CODE REVIEW

**Comment by rkh** [comment]
It's a typo. You cannot use include, since methods returns symbols in 1.9.

**Comment by simonc** [comment]
Understood. So using a == would do the trick then. Thanks.

**Comment by rkh** [comment]
Yeah, see 950ee916f9690f1097554acb691b936fdcb90ef3.

**Comment by simonc** [comment]
Perfect. Thanks !

**Pull request closed without merging**
