### PR TITLE
maybe pull?

### PR DESCRIPTION
**Pull request by dustalov**
I thought that using the Sugar library is overkill here and we really able to handle this tasks with standard tools of Ruby, Sinatra, etc.

Also, it's a reason to reduce dependency count in this tiny helpful piece of awesomeness and bump the minor version.

### CODE REVIEW

**Comment by rkh** [comment]
Yeah, I'm planning to dump sinatra-sugar all together. But this does affect a couple of more libs I have. I will look into this in depth after I'm back from vacation. But consider your patches merged (there is a conflict, so I didn't pull right away).

**Comment by dustalov** [comment]
Thanks. This conflict is pretty easy to resolve and put into the master branch.

**Comment by simonc** [comment]
Anything new on this subject ?

**Comment by dustalov** [comment]
fuck yea

**Pull request merged**
